In [1]:
# Data Types & Attributes
import numpy as np

In [2]:
# 1. Create a NumPy array arr of integers from 0 to 5 and print its data type.
arr1 = np.arange(6)
print("1. Data type of arr1:", arr1.dtype)

1. Data type of arr1: int32


In [3]:
# 2. Given a NumPy array arr, check if its data type is float64.
def is_float64(arr):
    return arr.dtype == np.float64

# Example:
arr2 = np.array([1.0, 2.0, 3.0], dtype=np.float64)
print("2. Is arr2 float64?", is_float64(arr2))

2. Is arr2 float64? True


In [4]:
# 3. Create a NumPy array arr with a data type of complex128 containing three complex numbers.
arr3 = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print("3. arr3 (complex128):", arr3)

3. arr3 (complex128): [1.+2.j 3.+4.j 5.+6.j]


In [5]:
# 4. Convert an existing NumPy array arr of integers to float32 data type.
arr4 = np.array([1, 2, 3, 4])
arr4_float32 = arr4.astype(np.float32)
print("4. arr4 converted to float32:", arr4_float32)

4. arr4 converted to float32: [1. 2. 3. 4.]


In [6]:
# 5. Given a NumPy array arr with float64 data type, convert it to float32 to reduce decimal precision.
arr5 = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr5_float32 = arr5.astype(np.float32)
print("5. arr5 converted to float32:", arr5_float32)

5. arr5 converted to float32: [1.1 2.2 3.3]


In [7]:
# 6. Function to return shape, size, and data type of an array.
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

# Example:
print("6. Attributes of arr2:", array_attributes(arr2))

6. Attributes of arr2: ((3,), 3, dtype('float64'))


In [8]:
# 7. Function to return the number of dimensions of a NumPy array.
def array_dimension(arr):
    return arr.ndim

# Example:
print("7. Dimensionality of arr3:", array_dimension(arr3))

7. Dimensionality of arr3: 1


In [9]:
# 8. Function to return item size and total size in bytes of an array.
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

# Example:
print("8. Item size and total size of arr4:", item_size_info(arr4))

8. Item size and total size of arr4: (4, 16)


In [10]:
# 9. Function to return the strides of the given NumPy array.
def array_strides(arr):
    return arr.strides

# Example:
print("9. Strides of arr1:", array_strides(arr1))

9. Strides of arr1: (4,)


In [11]:
# 10. Function to return shape and strides of an array.
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

# Example:
print("10. Shape and strides of arr5:", shape_stride_relationship(arr5))

10. Shape and strides of arr5: ((3,), (8,))


In [12]:
#     Array Creation

In [13]:
# 11. Create a function create_zeros_array(n) to return a NumPy array of zeros with n elements.
def create_zeros_array(n):
    return np.zeros(n)

print("11. Zeros array:", create_zeros_array(5))

11. Zeros array: [0. 0. 0. 0. 0.]


In [14]:
# 12. Write a function create_ones_matrix(rows, cols) to create a 2D array filled with ones.
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print("12. Ones matrix:\n", create_ones_matrix(2, 3))


12. Ones matrix:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# 13. Write a function generate_range_array(start, stop, step) to create a ranged NumPy array.
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print("13. Range array:", generate_range_array(0, 10, 2))

13. Range array: [0 2 4 6 8]


In [16]:
# 14. Design a function generate_linear_space(start, stop, num) for equally spaced values.
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print("14. Linear spaced array:", generate_linear_space(0, 1, 5))

14. Linear spaced array: [0.   0.25 0.5  0.75 1.  ]


In [17]:
# 15. Create a function create_identity_matrix(n) using numpy.eye.
def create_identity_matrix(n):
    return np.eye(n)

print("15. Identity matrix:\n", create_identity_matrix(4))


15. Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
# 16. Write a function that converts a Python list into a NumPy array.
def list_to_numpy_array(lst):
    return np.array(lst)

print("16. List to NumPy array:", list_to_numpy_array([1, 2, 3, 4]))


16. List to NumPy array: [1 2 3 4]


In [19]:
# 17. Create a NumPy array and use numpy.view() to create a new view with the same data.
original_array = np.array([10, 20, 30, 40])
view_array = original_array.view()

print("17. Original array:", original_array)
print("    View of array:", view_array)

17. Original array: [10 20 30 40]
    View of array: [10 20 30 40]


In [20]:
# Concatenation and Stacking


In [25]:

# Q18
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr1_q18 = np.array([[1, 2], [3, 4]])
arr2_q18 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(arr1_q18, arr2_q18, axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [26]:

# Q19
def concatenate_different_shapes_horizontally(arr1, arr2):
    arr1 = arr1.reshape(-1, 1) if arr1.ndim == 1 else arr1
    arr2 = arr2.reshape(-1, 1) if arr2.ndim == 1 else arr2
    return np.concatenate((arr1, arr2), axis=1)

arr1_q19 = np.array([1, 2, 3])
arr2_q19 = np.array([4, 5, 6])
print(concatenate_different_shapes_horizontally(arr1_q19, arr2_q19))

[[1 4]
 [2 5]
 [3 6]]


In [27]:

# Q20
def vertical_stack_arrays(array_list):
    return np.vstack(array_list)

print(vertical_stack_arrays([arr1_q19, arr2_q19]))

[[1 2 3]
 [4 5 6]]


In [29]:

# Q21
def generate_range_with_step(start, stop, step):
    return np.arange(start, stop + 1, step)

print(generate_range_with_step(1, 10, 2))

[1 3 5 7 9]


In [30]:

# Q22
print(np.linspace(0, 1, 10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [31]:
# Q23
print(np.logspace(0, 3, 5))

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [33]:
import pandas as pd

# Q24
def create_random_dataframe():
    data = np.random.randint(1, 101, size=(5, 3))
    return pd.DataFrame(data, columns=['A', 'B', 'C'])

df_q24 = create_random_dataframe()
print(df_q24)

    A   B    C
0  52  89    2
1  13  20  100
2  44  18   40
3  36  28   88
4  23  67   78


In [34]:

# Q25
def replace_negatives_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

df_q24.loc[1, 'B'] = -42  # Add negative value for testing
print(replace_negatives_with_zero(df_q24, 'B'))

    A   B    C
0  52  89    2
1  13   0  100
2  44  18   40
3  36  28   88
4  23  67   78


In [35]:
# Q26: Access the 3rd element from a 1D array
arr26 = np.array([10, 20, 30, 40, 50])
print(arr26[2])

30


In [36]:

# Q27: Retrieve element at index (1, 2) from 2D array
arr27 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr27[1, 2])

6


In [37]:

# Q28: Extract elements greater than 5 using boolean indexing
arr28 = np.array([2, 5, 8, 1, 9])
print(arr28[arr28 > 5])

[8 9]


In [38]:

# Q29: Slice elements from index 2 to 5 (inclusive)
arr29 = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(arr29[2:6])

[2 3 4 5]


In [39]:

# Q30: Slice sub-array [[2, 3], [5, 6]]
arr30 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr30[0:2, 1:3])

[[2 3]
 [5 6]]


In [40]:

# Q31: Extract elements based on indices from 2D array
arr31 = np.array([[10, 20, 30], [40, 50, 60]])
indices31 = [0, 1]
print(arr31[indices31, [1, 2]])

[20 60]


In [41]:

# Q32: Filter elements greater than threshold using boolean indexing
arr32 = np.array([1, 4, 7, 10])
print(arr32[arr32 > 5])

[ 7 10]


In [42]:

# Q33: Extract specific elements from a 3D array using index arrays
arr33 = np.arange(27).reshape(3, 3, 3)
i33 = np.array([0, 1])
j33 = np.array([1, 2])
k33 = np.array([2, 0])
print(arr33[i33, j33, k33])

[ 5 15]


In [43]:

# Q34: Elements satisfying two boolean conditions
arr34 = np.array([10, 15, 20, 25, 30])
print(arr34[(arr34 > 15) & (arr34 < 30)])

[20 25]


In [44]:

# Q35: Extract elements from 2D array using separate row and column index arrays
arr35 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows35 = np.array([0, 1, 2])
cols35 = np.array([2, 1, 0])
print(arr35[rows35, cols35])

[3 5 7]


In [45]:
# Q36: Add scalar 5 to every element using broadcasting
arr36 = np.array([1, 2, 3])
print(arr36 + 5)

[6 7 8]


In [46]:

# Q37: Multiply each row of (3, 4) array by (1, 3) array - corrected shape
arr37 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
row_multipliers = np.array([[1], [2], [3]])
print(arr37 * row_multipliers)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [48]:

# Q38: Add (1, 4) array to each row of (4, 3) array using broadcasting
import numpy as np

arr38 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])
                  
add38 = np.array([[10, 20, 30]])

print(arr38 + add38)

[[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]


In [49]:
import numpy as np

In [50]:
# Q39: Add arrays of shape (3, 1) and (1, 3) using broadcasting
arr39_a = np.array([[1], [2], [3]])
arr39_b = np.array([[10, 20, 30]])
print(arr39_a + arr39_b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [51]:

# Q40: Handle shape incompatibility during multiplication
arr40_a = np.array([[1, 2, 3], [4, 5, 6]])
arr40_b = np.array([[1, 2], [3, 4]])
try:
    print(arr40_a * arr40_b)
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (2,2) 


In [52]:

# Q41: Column-wise mean of a 2D array
arr41 = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr41, axis=0))

[2.5 3.5 4.5]


In [53]:
# Q42: Maximum value in each row
arr42 = np.array([[7, 2, 9], [1, 5, 3]])
print(np.max(arr42, axis=1))

[9 5]


In [54]:
# Q43: Indices of maximum values in each column
arr43 = np.array([[1, 4, 2], [7, 0, 5]])
print(np.argmax(arr43, axis=0))

[1 0 1]


In [55]:

# Q44: Moving sum along rows (custom function)
arr44 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
def moving_sum_rowwise(arr, window=2):
    return np.array([np.convolve(row, np.ones(window, dtype=int), 'valid') for row in arr])
print(moving_sum_rowwise(arr44, window=2))

[[ 3  5  7]
 [11 13 15]]


In [56]:

# Q45: Check if all elements in each column are even
arr45 = np.array([[2, 4], [6, 8]])
print(np.all(arr45 % 2 == 0, axis=0))

[ True  True]


In [57]:

# Q46: Reshape a given array into dimensions m x n
arr46 = np.arange(12)
print(arr46.reshape(3, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [58]:
# Q47: Flatten a given matrix
arr47 = np.array([[1, 2], [3, 4]])
print(arr47.flatten())

[1 2 3 4]


In [59]:

# Q48: Concatenate two arrays along a specified axis
arr48_1 = np.array([[1, 2], [3, 4]])
arr48_2 = np.array([[5, 6]])
print(np.concatenate((arr48_1, arr48_2), axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [60]:
# Q49: Split an array into sub-arrays along a specified axis
arr49 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.split(arr49, 2, axis=1))  # split into 2 sub-arrays column-wise


[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [61]:
# Q50: Insert and delete elements at specified indices
arr50 = np.array([10, 20, 30, 40])
arr50_inserted = np.insert(arr50, 2, 25)  # insert 25 at index 2
arr50_deleted = np.delete(arr50_inserted, 3)  # delete element at index 3
print(arr50_inserted)
print(arr50_deleted)


[10 20 25 30 40]
[10 20 25 40]


In [62]:
# Q51: Element-wise addition between two arrays
arr51_a = np.array([1, 2, 3])
arr51_b = np.array([4, 5, 6])
print(arr51_a + arr51_b)

[5 7 9]


In [63]:

# Q52: Element-wise subtraction (arr1 - arr2)
print(arr51_a - arr51_b)

# Q53: Element-wise multiplication
print(arr51_a * arr51_b)

# Q54: Element-wise division
print(arr51_a / arr51_b)

# Q55: Element-wise exponentiation (arr1 ** arr2)
print(arr51_a ** arr51_b)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [65]:
# Q56: Count occurrences of a substring in a string array
arr56 = np.array(['apple pie', 'banana pie', 'cherry tart'])
print(np.char.count(arr56, 'pie'))

[1 1 0]


In [66]:
# Q57: Extract uppercase characters from a string array
arr57 = np.array(['HeLLo', 'WorLD', 'PyTHon'])
print(np.array([''.join([ch for ch in s if ch.isupper()]) for s in arr57]))


['HLL' 'WLD' 'PTH']


In [67]:
# Q58: Replace substring occurrences with another string in a string array
arr58 = np.array(['hello world', 'python world'])
print(np.char.replace(arr58, 'world', 'universe'))


['hello universe' 'python universe']


In [68]:
# Q59: Concatenate strings in a NumPy array element-wise
arr59a = np.array(['foo', 'bar'])
arr59b = np.array(['123', '456'])
print(np.char.add(arr59a, arr59b))


['foo123' 'bar456']


In [69]:
# Q60: Find the length of the longest string in a string array
arr60 = np.array(['short', 'medium', 'a very long string'])
print(max(np.char.str_len(arr60)))

18


In [70]:
# Q61: Mean, median, variance, std of 100 random integers (1–1000)
arr61 = np.random.randint(1, 1001, 100)
print(np.mean(arr61))
print(np.median(arr61))
print(np.var(arr61))
print(np.std(arr61))

553.95
541.0
96967.46749999998
311.39599788693494


In [71]:
# Q62: 25th and 75th percentiles of 50 random numbers (1–100)
arr62 = np.random.randint(1, 101, 50)
print(np.percentile(arr62, 25))
print(np.percentile(arr62, 75))

29.0
79.0


In [72]:
# Q63: Correlation coefficient between two arrays
arr63a = np.array([1, 2, 3, 4, 5])
arr63b = np.array([2, 4, 6, 8, 10])
print(np.corrcoef(arr63a, arr63b))

[[1. 1.]
 [1. 1.]]


In [73]:

# Q64: Matrix multiplication using np.dot
arr64a = np.array([[1, 2], [3, 4]])
arr64b = np.array([[5, 6], [7, 8]])
print(np.dot(arr64a, arr64b))


[[19 22]
 [43 50]]


In [74]:
# Q65: 10th, 50th, 90th percentiles of array of 50 integers
arr65 = np.random.randint(1, 101, 50)
print(np.percentile(arr65, [10, 50, 90]))

# Q66: Find index of a specific element in array
arr66 = np.array([10, 20, 30, 40, 50])
print(np.where(arr66 == 30)[0][0])

# Q67: Sort a random array in ascending order
arr67 = np.random.randint(1, 100, 10)
print(np.sort(arr67))

# Q68: Filter elements greater than 20
arr68 = np.array([5, 15, 25, 35])
print(arr68[arr68 > 20])

# Q69: Filter elements divisible by 3
arr69 = np.array([3, 5, 9, 10, 12])
print(arr69[arr69 % 3 == 0])

# Q70: Filter elements between 20 and 40 (inclusive)
arr70 = np.array([10, 25, 35, 45])
print(arr70[(arr70 >= 20) & (arr70 <= 40)])

# Q71: Check byte order of a NumPy array
arr71 = np.array([1, 2, 3])
print(arr71.dtype.byteorder)

# Q72: Perform in-place byte swapping using byteswap()
arr72 = np.array([1, 256], dtype='>i2')  # big-endian 2-byte integers
arr72.byteswap(True)
print(arr72)

[18.  47.  93.1]
2
[ 7 11 22 27 27 30 43 68 75 76]
[25 35]
[ 3  9 12]
[25 35]
=
[256   1]
